version: '3.9'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" #map port to docker container port
    volumes:
      - ./app:/app
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=mysecretkey
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=myusername
#      - POSTGRES_PASSWORD=mypassword
#    depends_on:
#      - db
#
#  db:
#    image: postgres:13.1-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=myusername
#      - POSTGRES_PASSWORD=mypassword
#
#volumes:
#  postgres_data:
